services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGTZ=Asia/Damascus
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      mpu-network:
        ipv4_address: 172.28.0.105

  webgoat:
    image: webgoat/webgoat
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      mpu-network:
        ipv4_address: 172.28.0.104

  backend:
    build:
      context: ./dashboard/backend
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      mpu-network:
        ipv4_address: 172.28.0.103

  frontend:
    build:
      context: ./dashboard/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      mpu-network:
        ipv4_address: 172.28.0.102

  alerts_watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    user: root
    volumes:
      - ./snort_logs:/app/snort_logs
      - ml_alerts:/app/ml_alerts 
    environment:
      - BACKEND_URL=http://backend:8000/api/alerts/ingest
      - TZ=Asia/Damascus
      - ML_ALERT_FILE=/app/ml_alerts/alerts.log
    depends_on:
      - backend
    networks:
      mpu-network:
        ipv4_address: 172.28.0.101
    restart: unless-stopped

  snort:
    image: ciscotalos/snort3:latest
    hostname: snort3
    user: root
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./snort_logs:/var/log/snort
      - ./snort/snort.lua:/etc/snort/snort.lua
      - ./snort/rules:/etc/snort/rules
      - ./snort/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command: []

  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      mpu-network:
        ipv4_address: 172.28.0.99
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=mpu
      - N8N_BASIC_AUTH_PASSWORD=123
      - GENERIC_TIMEZONE=Asia/Damascus
      - TZ=Asia/Damascus
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost/n8n/
      - N8N_PATH=/n8n/
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      mpu-network:
        ipv4_address: 172.28.0.100
    restart: unless-stopped

  ml_detector:
    build: ./ml_model
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - MODEL_PATH=/app/models/isolation_forest.joblib
      - ALERT_LOG_PATH=/var/log/ml_detector/alerts.log
      - SOURCE_TYPE=ml_anomaly
      - IFACE=enp0s3
      - SCALER_PATH=/app/models/scaler.joblib
      - MODEL_VERSION=hybrid_v2
      - FLOW_CSV_PATH=/var/log/ml_detector/flows.csv
      - SCAN_MODEL_PATH=/app/models/scan_persistent_model.joblib
      - SCAN_SCALER_PATH=/app/models/scan_persistent_scaler.joblib
      - SCAN_WINDOW_SECONDS=60
      - SCAN_THRESHOLD=-0.15
    volumes:
      - ./models:/app/models:ro          
      - ml_alerts:/var/log/ml_detector  
volumes:
  db_data:
  ml_alerts:
networks:
  mpu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
